### ISSUE TITLE
Broken on C:S 1.1.1c patch

### ISSUE THREAD

**Issue by originalfoo** [DirtyDan88/Skylines-ControlBuildingLevelUpMod#2]
Hi - seems there are some errors with latest patch, which is a shame because this mod is awesome for rural villages! Details posted on workshop page.

**Comment by DirtyDan88** [comment]
Hi, thanks for reporting! I hadn't the time to play CS and maintain the mod for a long time... I started playing again this week, but I didn't notice any problems/crashes with my mod and the current CS vesion. Maybe some other mod causes your problems?

**Comment by armarayo** [comment]
For my experience, this mod works perfectly with 1.1.1c
