### ISSUE TITLE
After Dark compatibility

### ISSUE THREAD

**Issue by armarayo** [DirtyDan88/Skylines-ControlBuildingLevelUpMod#3]
After Dark expansion is doing some changes to district info UI, so this mod most likely needs updating/checking.

Will you please do it soon as AD is out. This mod is a must have
(and should be included in the game :) )

**Comment by DirtyDan88** [comment]
Hey, 
Thanks! :) AD does change the UI? Where did you get that info from? (sorry I am not really into CS atm)
If that is indeed the case, I will try to fix it as far as it is possible for me.

**Comment by armarayo** [comment]
There are new options in the district panel, so your mod might not work. We'll see tomorrow.
I got the info from dev diary, there is a district building style drop down menu added. Hopefully it doesn't interfere with your mod - but they have reworked the district panel so..

:)

**Comment by armarayo** [comment]
This mod has been reported working. So you can close this issue :)

**Comment by DirtyDan88** [comment]
Oh, without any effort, thats great to hear! :) 

I will of course also try AD when I find the time, but please continue reporting if problems appear. I will not make any promises, but it's also in my interest to keep this mod working! 

Cheers!
